name: CS102 Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black mypy pylint
    - name: Run black
      run: |
        black -l 100 --check --diff --color --exclude "test*" homework07-web
    - name: Run mypy
      run: |
        mypy --ignore-missing-imports ${{ github.head_ref }} --exclude "tests"
    - name: Run pylint
      run: |
        pylint --exit-zero ${{ github.head_ref }}
    - name: Run PyTest
      run: |
        pytest ${{ github.head_ref }}